### PR TITLE
Moved from CUDArt to CUDAdrv

### PR DESCRIPTION
**Pull request by dfdx**

### CODE REVIEW

**Comment by MikeInnes** [comment]
Seems reasonable to me. Looks like travis just shouldn't be enabled for this repo.

Might be worth setting up CI (cc @maleadt)

**Comment by maleadt** [comment]
~~Note sure why that didn't trigger CI. Should be enabled, maybe a (force) push will work.~~

CI works after https://github.com/maleadt/juliagpu-buildbot/commit/8833bd1542be434415285d65eb3f39049d00c4a9

**Comment by dfdx** [comment]
1. Turned off Travis for this repo after realizing that build badge actually comes from Tim's servers. 
2. Do we need to support Julia 0.5 in this repo? On one hand, it's easy to keep compatibility. On the other hand, many packages in JuliaGPU are already 0.6 only so most people will want to use it anyway.

**Comment by maleadt** [comment]
> Do we need to support Julia 0.5 in this repo? On one hand, it's easy to keep compatibility. On the other hand, many packages in JuliaGPU are already 0.6 only so most people will want to use it anyway.

Let me know if I need to disable 0.5 for this repo.

**Comment by MikeInnes** [comment]
Yeah, I recommend just dropping 0.5 for simplicity.

**Comment by dfdx** [comment]
> Let me know if I need to disable 0.5 for this repo.

Yes, please. I've already removed 0.5 badge from the README, so you just need to turn it off on your server.

**Comment by maleadt** [comment]
OK, disabled 0.5. Failing status will remain on this PR though.

**Comment by dfdx** [comment]
Thanks!

**Pull request merged**
